plugins {
    id 'com.android.application'
}

def appVersion = new Properties()
rootProject.file('version.properties').withInputStream { appVersion.load(it) }

android {
    namespace 'vn.nanase.hako'
    compileSdk 34

    defaultConfig {
        applicationId 'vn.nanase.hako'
        minSdk 26
        targetSdk 34
        versionCode appVersion.VERSION_CODE.toInteger()
        versionName appVersion.VERSION_NAME
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    signingConfigs {
        debug {
            storeFile file('../test-signing.p12')
            storePassword 'android'
            keyAlias 'hako-test'
            keyPassword 'android'
            storeType 'PKCS12'
        }
        release {
            storeFile file('../test-signing.p12')
            storePassword 'android'
            keyAlias 'hako-test'
            keyPassword 'android'
            storeType 'PKCS12'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.12.0'
    implementation 'org.jsoup:jsoup:1.18.3'
}

