plugins {
    id 'com.android.application'
}

android {
    namespace 'vn.nanase.hako'
    compileSdk 35

    defaultConfig {
        applicationId 'vn.nanase.hako'
        minSdk 26
        targetSdk 34
        ndk { abiFilters(project.findProperty("abi") ?: "armeabi-v7a") }
        versionCode 17
        versionName '0.7.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        jniLibs { useLegacyPackaging = true }
    }

    signingConfigs {
        signingKey {
            storeFile file('../test-signing.p12')
            storePassword 'android'
            keyAlias 'hako-test'
            keyPassword 'android'
            storeType 'PKCS12'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.signingKey
        }
        release {
            signingConfig signingConfigs.signingKey
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation "org.mozilla.geckoview:geckoview-${project.findProperty('abi') ?: 'armeabi-v7a'}:${project.findProperty('geckoVersion') ?: rootProject.file('gecko-version.txt').text.trim()}"
    implementation 'androidx.core:core:1.12.0'
    implementation 'org.jsoup:jsoup:1.18.3'
}
